package com.hmx.ssm.demo1.model;

import java.io.Serializable;

public class Role implements Serializable {



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLEID
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLENAME
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    public Role(String roleid,String rolename) {
        this.roleid = roleid;
        this.rolename = rolename;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLEID
     *
     * @return the value of role.ROLEID
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLEID
     *
     * @param roleid the value for role.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLENAME
     *
     * @return the value of role.ROLENAME
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLENAME
     *
     * @param rolename the value for role.ROLENAME
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{roleid=").append(roleid);
        sb.append(", rolename=").append(rolename);
        sb.append("}");
        return sb.toString();
    }
}